services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: panko_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  panko:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/panko_dev
      # IMPORTANT: Replace this with a real secret in production!
      # Generate one with: mix phx.gen.secret
      SECRET_KEY_BASE: c3320bd6cf3a7e336dbf7564d67701475b35a34045b232c2c1b99b825f8ac65961cc789829742dd7b8003f7fd811b90b23468039417072fb75dcba31adc5e58a
      PHX_HOST: localhost
      PHX_SERVER: "true"
      PORT: "4000"
    ports:
      - "4000:4000"

volumes:
  pgdata:
