defmodule Panko.Repo.Migrations.CreateSubAgents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sub_agents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:external_id, :text, null: false)
      add(:agent_type, :text, null: false)
      add(:description, :text)
      add(:prompt, :text)
      add(:status, :text, null: false)
      add(:result, :text)
      add(:spawned_at, :utc_datetime, null: false)
      add(:completed_at, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :session_id,
        references(:sessions,
          column: :id,
          name: "sub_agents_session_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:sub_agents, "sub_agents_session_id_fkey"))

    drop(table(:sub_agents))
  end
end
