defmodule Panko.Repo.Migrations.CreateShares do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:shares, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:slug, :text, null: false)
      add(:is_shared, :boolean, null: false, default: true)
      add(:expires_at, :utc_datetime)
      add(:shared_at, :utc_datetime, null: false)
      add(:unshared_at, :utc_datetime)
      add(:user_id, :uuid)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :session_id,
        references(:sessions,
          column: :id,
          name: "shares_session_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:shares, [:slug], name: "shares_unique_slug_index")
  end

  def down do
    drop_if_exists(unique_index(:shares, [:slug], name: "shares_unique_slug_index"))

    drop(constraint(:shares, "shares_session_id_fkey"))

    drop(table(:shares))
  end
end
