defmodule Panko.Repo.Migrations.CreateSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sessions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:external_id, :text, null: false)
      add(:source_type, :text, null: false)
      add(:source_path, :text)
      add(:project, :text)
      add(:title, :text)
      add(:started_at, :utc_datetime, null: false)
      add(:user_id, :uuid)
      add(:origin_id, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:sessions, [:external_id, :source_type],
        name: "sessions_external_id_source_type_index"
      )
    )
  end

  def down do
    drop_if_exists(
      unique_index(:sessions, [:external_id, :source_type],
        name: "sessions_external_id_source_type_index"
      )
    )

    drop(table(:sessions))
  end
end
