defmodule Panko.Repo.Migrations.CreateBlocks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:blocks, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:position, :bigint, null: false)
      add(:block_type, :text, null: false)
      add(:content, :text)
      add(:metadata, :map)
      add(:timestamp, :utc_datetime)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :session_id,
        references(:sessions,
          column: :id,
          name: "blocks_session_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(index(:blocks, [:session_id, :position], unique: true))

    create(unique_index(:blocks, [:session_id, :position], name: "blocks_session_position_index"))
  end

  def down do
    drop_if_exists(
      unique_index(:blocks, [:session_id, :position], name: "blocks_session_position_index")
    )

    drop(constraint(:blocks, "blocks_session_id_fkey"))

    drop_if_exists(index(:blocks, [:session_id, :position]))

    drop(table(:blocks))
  end
end
